name: Repo Action
on: 
  push:
    branches:
    - main
    # paths-ignore:
    # - '.github/workflows/**'

    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.2.2
    - name: Archive Files
      run: |
        zip -r web.zip . -i web-api/dist/**/*
        ls -R
    - name: upload
      uses: actions/upload-artifact@v4.6.1
      with:
        name: web2
        # path: web-api/dist/**
        path: web.zip
        compression-level: 0
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download
        uses: actions/download-artifact@v4.1.9
        with:
          name: web2
      - name: unarchive
        run: unzip web.zip
      - run: ls -R
      
