name: pipe
on: workflow_dispatch

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.2.2
    # - name: Archive Files
    #   run: |
    #     zip -r web.zip . -i web-api/dist/**/*
    #     ls -R
    - name: upload
      uses: actions/upload-artifact@v4.6.1
      with:
        name: web
        path: web-api/dist/**
  second:
    runs-on: ubuntu-latest
    steps:
      - name: download
        uses: actions/download-artifact@v4.1.9
        with:
          name: web
        
      
